### ISSUE TITLE
Circle Customization?

### ISSUE THREAD

**Issue by Khyzar** [iamanvesh/mapbox-gl-draw-circle#17]
Is there any way to customize the circle? By customization: I mean to change the color. Is there any way as well to disable the creation of circle by click so that I can add multiple circles on the map?

**Comment by iamanvesh** [comment]
All of this can be achieved using the mapbox draw library itself. This module just adds the ability to draw a circle. The underlying feature can be customised just as how you would do for a polygon using draw. Refer to [this](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#styling-draw) section of the documentation for more information.

Coming to the multiple circles, its already supported. You just need to switch to circle mode again. The sample app I made clears all the features that are on the map when you switch between modes which is why it only creates one circle.

**Comment by Khyzar** [comment]
I get it how to customize the circle using the styling but can you tell me how I can make the call to draw a circle on button click instead of first click on the map, as I dont see any mouse click code overwritten in ur code.
I am new to mapbox

**Comment by iamanvesh** [comment]
The demo app is [here](https://github.com/iamanvesh/mapbox-gl-draw-circle-test). You can find the click listeners etc, in this repo..
